let Int i;
let ^Float[1] f;

let Float q = 1 + i + f;
let Float q = 1 + i;
let Float q = 1 + i + ----^(f[0]);
True == False <= 1;
let Bool b = (True == !!!!False == False);

def F() => Float {}
F(); 

let Char a = F();
let Float w = (1 + i) --^(f[0]) ** F(); 

let Char[5] hello = ['W', 0, 'r', 'l', 'd'];
let String[5] lorem = ["Ipsu", "No ", ['S', 'e', ' ', 'q', 'u', 'e'], "poner"];

${
  (4, 25): Error: Operator '+' don't matches with operand types: 'Int' and '(^(Float))[]'.
  (5, 21): Error: Can't assign a 'Int' to a 'Float'.
  (7, 20): Error: Operator '<=' don't matches with operand types: 'Bool' and 'Int'.
  (13, 18): Error: Can't assign a 'Float' to a 'Char'.
  (16, 29): Error: All elements of an array must have the same type, but found 'Char' and 'Int'.
}$